Repository HwaRoak/HwaRoak_BE, pull requests merged in 2025-08, with the labels that each got.

#93 [Feat] 스케줄러를 이용한 월간 리포트 알림 추가
  src/main/java/com/umc/hwaroak/domain/common/AlarmType.java
  src/main/java/com/umc/hwaroak/repository/AlarmRepository.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmServiceImpl.java
Labels: ✨ feature

#94 [feat] S3를 이용해서 프로필 사진 업로드 및 삭제하기
  build.gradle
  src/main/java/com/umc/hwaroak/config/S3Config.java
  src/main/java/com/umc/hwaroak/controller/MemberController.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/dto/request/MemberRequestDto.java
  src/main/java/com/umc/hwaroak/dto/response/MemberResponseDto.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/MemberService.java
  src/main/java/com/umc/hwaroak/service/S3Service.java
  src/main/java/com/umc/hwaroak/serviceImpl/KakaoAuthServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/S3ServiceImpl.java
  src/main/java/com/umc/hwaroak/util/ImageFormatter.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
Labels: ✨ feature

#100 [fix]알림 설정 변경 api 관련 오류 수정
  src/main/java/com/umc/hwaroak/controller/MemberController.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmSettingServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
Labels: 🚨 fix, 🐛 bug

#105 DEPLOY 1.5.0 - 아이템 및 회원 관련 부가 기능 추가
  build.gradle
  nginx/nginx.conf
  src/main/java/com/umc/hwaroak/config/S3Config.java
  src/main/java/com/umc/hwaroak/controller/AlarmController.java
  src/main/java/com/umc/hwaroak/controller/DiaryController.java
  src/main/java/com/umc/hwaroak/controller/ItemController.java
  src/main/java/com/umc/hwaroak/controller/MemberController.java
  src/main/java/com/umc/hwaroak/controller/QuestionController.java
  src/main/java/com/umc/hwaroak/converter/ItemConverter.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/domain/MemberAnswer.java
  src/main/java/com/umc/hwaroak/domain/MemberItem.java
  src/main/java/com/umc/hwaroak/domain/Question.java
  src/main/java/com/umc/hwaroak/domain/common/AlarmType.java
  src/main/java/com/umc/hwaroak/dto/request/MemberRequestDto.java
  src/main/java/com/umc/hwaroak/dto/response/ItemResponseDto.java
  src/main/java/com/umc/hwaroak/dto/response/MemberResponseDto.java
  src/main/java/com/umc/hwaroak/dto/response/QuestionResponseDto.java
  src/main/java/com/umc/hwaroak/repository/AlarmRepository.java
  src/main/java/com/umc/hwaroak/repository/DiaryRepository.java
  src/main/java/com/umc/hwaroak/repository/ItemRepositoryCustom.java
  src/main/java/com/umc/hwaroak/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/umc/hwaroak/repository/MemberItemRepository.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository.java
  src/main/java/com/umc/hwaroak/repository/QuestionRepository.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/ItemService.java
  src/main/java/com/umc/hwaroak/service/MemberService.java
  src/main/java/com/umc/hwaroak/service/QuestionService.java
  src/main/java/com/umc/hwaroak/service/S3Service.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmSettingServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/DiaryServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/ItemServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/KakaoAuthServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/QuestionServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/S3ServiceImpl.java
  src/main/java/com/umc/hwaroak/util/ImageFormatter.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
Labels: 🌐 Deploy

#110 [fix] 알림 설정 로직 변경
  src/main/java/com/umc/hwaroak/controller/ItemController.java
  src/main/java/com/umc/hwaroak/dto/response/QuestionResponseDto.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmSettingServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/QuestionServiceImpl.java
Labels: 🚨 fix, 🐛 bug

#116 [fix] 신규 가입 시 기본 아이템 로직 변경
  src/main/java/com/umc/hwaroak/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/ItemServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/KakaoAuthServiceImpl.java
Labels: 🚨 fix, 🐛 bug

#120 [fix] 전체 알람 조회시 userId 반환되게끔 추가
  src/main/java/com/umc/hwaroak/controller/AlarmController.java
  src/main/java/com/umc/hwaroak/dto/response/AlarmResponseDto.java
  src/main/java/com/umc/hwaroak/repository/AlarmRepository.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmServiceImpl.java
Labels: 🐛 bug

#119 [refactor] EventListener로 변경하기
  nginx/nginx.conf
  src/main/java/com/umc/hwaroak/config/RedisPubSubConfig.java
  src/main/java/com/umc/hwaroak/config/SecurityConfig.java
  src/main/java/com/umc/hwaroak/domain/Question.java
  src/main/java/com/umc/hwaroak/domain/common/AlarmType.java
  src/main/java/com/umc/hwaroak/event/FireSendEvent.java
  src/main/java/com/umc/hwaroak/event/FriendRequestEvent.java
  src/main/java/com/umc/hwaroak/event/ItemRollbackEvent.java
  src/main/java/com/umc/hwaroak/event/ItemUpdateEvent.java
  src/main/java/com/umc/hwaroak/infrastructure/authentication/JwtAuthenticationEntryPoint.java
  src/main/java/com/umc/hwaroak/infrastructure/authentication/JwtAuthenticationFilter.java
  src/main/java/com/umc/hwaroak/infrastructure/authentication/JwtTokenProvider.java
  src/main/java/com/umc/hwaroak/infrastructure/authentication/MemberLoader.java
  src/main/java/com/umc/hwaroak/infrastructure/publisher/RedisPublisher.java
  src/main/java/com/umc/hwaroak/infrastructure/subscriber/RedisSubscriber.java
  src/main/java/com/umc/hwaroak/infrastructure/transaction/CustomTransactionSynchronization.java
  src/main/java/com/umc/hwaroak/listener/FireEventListener.java
  src/main/java/com/umc/hwaroak/listener/FriendEventListener.java
  src/main/java/com/umc/hwaroak/listener/ItemEventListener.java
  src/main/java/com/umc/hwaroak/scheduler/AlarmScheduler.java
  src/main/java/com/umc/hwaroak/scheduler/EmotionScheduler.java
  src/main/java/com/umc/hwaroak/service/AlarmService.java
  src/main/java/com/umc/hwaroak/service/ItemService.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmSettingServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/DiaryServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/EmitterServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/EmotionSummaryServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/FriendServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/ItemServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/KakaoAuthServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/QuestionServiceImpl.java
  src/main/java/com/umc/hwaroak/util/SseRepositoryKeyGenerator.java
Labels: ♻️ refactor

#129 [feat] 친구 아이템 리스트 조회 api 추가 및 수정
  src/main/java/com/umc/hwaroak/controller/FriendController.java
  src/main/java/com/umc/hwaroak/dto/response/FriendResponseDto.java
  src/main/java/com/umc/hwaroak/service/FriendService.java
  src/main/java/com/umc/hwaroak/serviceImpl/FriendServiceImpl.java
Labels: 🚨 fix, ✨ feature

#134 DEPLOY 1.6.3 - 친구 알림 전송 오류 수정
  src/main/java/com/umc/hwaroak/serviceImpl/FriendServiceImpl.java
Labels: 🌐 Deploy

#137 [fix] Presigned Url 이용해서 S3에 업로드 하기
  src/main/java/com/umc/hwaroak/controller/MemberController.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/dto/request/MemberRequestDto.java
  src/main/java/com/umc/hwaroak/dto/response/MemberResponseDto.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/MemberService.java
  src/main/java/com/umc/hwaroak/service/S3Service.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/S3ServiceImpl.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
Labels: 🚨 fix, 🐛 bug

#140 [fix] 다음 보상 아이템으로 넘어가지 않는 오류 해결
  build.gradle
  src/main/java/com/umc/hwaroak/controller/AuthController.java
  src/main/java/com/umc/hwaroak/domain/Alarm.java
  src/main/java/com/umc/hwaroak/domain/Diary.java
  src/main/java/com/umc/hwaroak/domain/Item.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/event/listener/FireEventListener.java
  src/main/java/com/umc/hwaroak/event/listener/FriendEventListener.java
  src/main/java/com/umc/hwaroak/event/listener/ItemEventListener.java
  src/main/java/com/umc/hwaroak/repository/ItemRepository.java
  src/main/java/com/umc/hwaroak/repository/ItemRepositoryCustom.java
  src/main/java/com/umc/hwaroak/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/AlarmServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/AlarmSettingServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/DiaryServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/EmitterServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/EmotionSummaryServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/FriendServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/ItemServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/KakaoAuthServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/MemberServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/QuestionServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/S3ServiceImpl.java
Labels: 🚨 fix

#147 [feat] Log 별도 관리하기
  .gitignore
  docker-compose.yml
  src/main/java/com/umc/hwaroak/exception/GlobalExceptionHandler.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
  src/main/resources/logback-dev.yaml
  src/main/resources/logback-local.yaml
  src/main/resources/logback-spring.xml
Labels: ✨ feature

#153 DEPLOY - 1.6.5 성능 개선 리팩토링 및 HTTPS 발급
  .github/workflows/deploy.yml
  docker-compose.yml
  nginx/nginx.conf
  src/main/java/com/umc/hwaroak/config/AsyncConfig.java
  src/main/java/com/umc/hwaroak/config/SwaggerConfig.java
  src/main/java/com/umc/hwaroak/domain/Alarm.java
  src/main/java/com/umc/hwaroak/event/SummaryMessageGenerateEvent.java
  src/main/java/com/umc/hwaroak/event/listener/SummaryMessageListener.java
  src/main/java/com/umc/hwaroak/repository/EmotionSummaryRepository.java
  src/main/java/com/umc/hwaroak/service/DiaryTransactionalService.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/DiaryServiceImpl.java
  src/main/java/com/umc/hwaroak/service/serviceImpl/EmotionSummaryServiceImpl.java
  src/main/java/com/umc/hwaroak/util/OpenAiUtil.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
Labels: 🌐 Deploy
