Repository HwaRoak/HwaRoak_BE, pull requests merged in 2025-07, with the labels that each got.

#9 Merge Develop to Main for check CI/CD
  .DS_Store
  .github/workflows/deploy.yml
  .gitignore
  appspec.yml
  build.gradle
  gradle/.DS_Store
  gradlew
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/application-dev.yaml
Labels: 👷 CI/CD

#10 Merge Develop to Main for check CI/CD 2
  scripts/start.sh
  scripts/stop.sh
Labels: 👷 CI/CD

#11 Merge develop to main for check CI/CD 3
  scripts/stop.sh
Labels: 👷 CI/CD

#13 [feat] 회원 정보 조회 api 구현
  README.md
  src/main/java/com/umc/hwaroak/controller/MemberController.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/dto/MemberResponseDto.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository/MemberRepository.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/MemberService.java
  src/main/java/com/umc/hwaroak/service/MemberServiceImpl.java
Labels: ✨ feature

#17 [feat] 친구 기능 api 구현
  src/main/java/com/umc/hwaroak/HwaroakApplication.java
  src/main/java/com/umc/hwaroak/controller/AlarmController.java
  src/main/java/com/umc/hwaroak/controller/FriendController.java
  src/main/java/com/umc/hwaroak/domain/Friend.java
  src/main/java/com/umc/hwaroak/domain/common/FriendStatus.java
  src/main/java/com/umc/hwaroak/dto/FriendRequestDto.java
  src/main/java/com/umc/hwaroak/dto/FriendResponseDto.java
  src/main/java/com/umc/hwaroak/repository/FriendRepository.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/FriendService.java
  src/main/java/com/umc/hwaroak/service/FriendServiceImpl.java
Labels: ✨ feature

#18 [feat] 일기 기능 구현
  .DS_Store
  build.gradle
  gradle/.DS_Store
  src/main/java/com/umc/hwaroak/controller/DiaryController.java
  src/main/java/com/umc/hwaroak/controller/TestController.java
  src/main/java/com/umc/hwaroak/converter/.gitkeep
  src/main/java/com/umc/hwaroak/converter/DiaryConverter.java
  src/main/java/com/umc/hwaroak/domain/Diary.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/dto/.gitkeep
  src/main/java/com/umc/hwaroak/dto/request/DiaryRequestDto.java
  src/main/java/com/umc/hwaroak/dto/response/DiaryResponseDto.java
  src/main/java/com/umc/hwaroak/repository/.gitkeep
  src/main/java/com/umc/hwaroak/repository/DiaryRepository.java
  src/main/java/com/umc/hwaroak/repository/DiaryRepositoryCustom.java
  src/main/java/com/umc/hwaroak/repository/DiaryRepositoryCustomImpl.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository/MemberRepository.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository/MemberRepositoryCustom.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository/MemberRepositoryImpl.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/DiaryService.java
  src/main/java/com/umc/hwaroak/service/DiaryServiceImpl.java
  src/main/java/com/umc/hwaroak/service/MemberServiceImpl.java
  src/main/java/com/umc/hwaroak/util/.gitkeep
  src/main/java/com/umc/hwaroak/util/OpenAiUtil.java
  src/main/resources/application-local.yaml
Labels: ✨ feature

#23 [feat] 회원 정보 기능 구현
  src/main/java/com/umc/hwaroak/controller/MemberController.java
  src/main/java/com/umc/hwaroak/converter/MemberConverter.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/dto/MemberResponseDto.java
  src/main/java/com/umc/hwaroak/dto/request/MemberRequestDto.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/MemberService.java
  src/main/java/com/umc/hwaroak/service/MemberServiceImpl.java
Labels: ✨ feature

#39 [feat] 아이템 관련 기능 구현
  src/main/java/com/umc/hwaroak/controller/MemberController.java
  src/main/java/com/umc/hwaroak/domain/Item.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/domain/MemberItem.java
  src/main/java/com/umc/hwaroak/domain/common/Item.java
  src/main/java/com/umc/hwaroak/dto/response/DiaryResponseDto.java
  src/main/java/com/umc/hwaroak/dto/response/MemberResponseDto.java
  src/main/java/com/umc/hwaroak/repository/ItemRepository.java
  src/main/java/com/umc/hwaroak/repository/MemberItemRepository.java
  src/main/java/com/umc/hwaroak/repository/MemberRepository.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/response/ResponseWrappingAdvice.java
  src/main/java/com/umc/hwaroak/service/MemberService.java
  src/main/java/com/umc/hwaroak/serviceImpl/KakaoAuthServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
Labels: ✨ feature

#45 [fix] 카카오 JWT 토큰 발급 수정
  src/main/java/com/umc/hwaroak/authentication/JwtTokenProvider.java
  src/main/java/com/umc/hwaroak/exception/JwtExceptionHandler.java
  src/main/java/com/umc/hwaroak/serviceImpl/KakaoAuthServiceImpl.java
Labels: 🚨 fix

#47 [feat] 회원 고유아이디 발급 및 인증 재설정
  src/main/java/com/umc/hwaroak/authentication/JwtTokenProvider.java
  src/main/java/com/umc/hwaroak/authentication/MemberLoader.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/dto/response/MemberResponseDto.java
  src/main/java/com/umc/hwaroak/dto/response/TokenDto.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/serviceImpl/KakaoAuthServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
  src/main/java/com/umc/hwaroak/util/UidGenerator.java
Labels: ✨ feature

#48 [feat] 알림 설정 관련 기능 구현
  src/main/java/com/umc/hwaroak/controller/AlarmSettingController.java
  src/main/java/com/umc/hwaroak/domain/AlarmSetting.java
  src/main/java/com/umc/hwaroak/dto/request/AlarmSettingRequestDto.java
  src/main/java/com/umc/hwaroak/dto/response/AlarmSettingResponseDto.java
  src/main/java/com/umc/hwaroak/repository/AlarmSettingRepository.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/AlarmSettingService.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmSettingServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
Labels: ✨ feature

#58 [feat] 아이템 및 보상 관련 기능 구현
  src/main/java/com/umc/hwaroak/controller/DiaryController.java
  src/main/java/com/umc/hwaroak/converter/DiaryConverter.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/domain/MemberItem.java
  src/main/java/com/umc/hwaroak/dto/response/DiaryResponseDto.java
  src/main/java/com/umc/hwaroak/repository/DiaryRepository.java
  src/main/java/com/umc/hwaroak/repository/DiaryRepositoryCustom.java
  src/main/java/com/umc/hwaroak/repository/DiaryRepositoryCustomImpl.java
  src/main/java/com/umc/hwaroak/repository/ItemRepository.java
  src/main/java/com/umc/hwaroak/service/AlarmService.java
  src/main/java/com/umc/hwaroak/service/DiaryService.java
  src/main/java/com/umc/hwaroak/serviceImpl/DiaryServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/KakaoAuthServiceImpl.java
  src/main/java/com/umc/hwaroak/util/OpenAiUtil.java
Labels: ✨ feature

#60 [deploy] Docker를 통한 무중단배포로의 변경
  .github/workflows/deploy.yml
  deploy.sh
  docker-compose.yml
  nginx/nginx.conf
Labels: 👷 CI/CD, 🌐 Deploy

#59 [feat] 친구에게 불씨 보내기
  src/main/java/com/umc/hwaroak/controller/FriendController.java
  src/main/java/com/umc/hwaroak/domain/Alarm.java
  src/main/java/com/umc/hwaroak/domain/common/BaseEntity.java
  src/main/java/com/umc/hwaroak/dto/response/AlarmResponseDto.java
  src/main/java/com/umc/hwaroak/dto/response/FireAlarmResponseDto.java
  src/main/java/com/umc/hwaroak/repository/AlarmRepository.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/AlarmService.java
  src/main/java/com/umc/hwaroak/service/FriendService.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/FriendServiceImpl.java
  src/main/resources/application.yaml
Labels: ✨ feature

#63 [feat] 감정분석 관련 기능 구현
  src/main/java/com/umc/hwaroak/controller/EmotionSummaryController.java
  src/main/java/com/umc/hwaroak/domain/EmotionSummary.java
  src/main/java/com/umc/hwaroak/domain/Member.java
  src/main/java/com/umc/hwaroak/domain/common/Emotion.java
  src/main/java/com/umc/hwaroak/domain/common/EmotionCategory.java
  src/main/java/com/umc/hwaroak/dto/response/EmotionSummaryResponseDto.java
  src/main/java/com/umc/hwaroak/repository/DiaryRepositoryCustom.java
  src/main/java/com/umc/hwaroak/repository/DiaryRepositoryCustomImpl.java
  src/main/java/com/umc/hwaroak/repository/EmotionSummaryRepository.java
  src/main/java/com/umc/hwaroak/service/EmotionSummaryService.java
  src/main/java/com/umc/hwaroak/serviceImpl/DiaryServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/EmotionSummaryServiceImpl.java
  src/main/java/com/umc/hwaroak/util/OpenAiUtil.java
Labels: ✨ feature

#66 [Fix] 알람 조회시 시 분 초 까지 반환되게끔 수정
  src/main/java/com/umc/hwaroak/dto/response/AlarmResponseDto.java
  src/main/resources/application.yaml
Labels: 🚨 fix

#71 [Feat] 회원 검색하기 구현
  src/main/java/com/umc/hwaroak/controller/FriendController.java
  src/main/java/com/umc/hwaroak/dto/request/FriendRequestDto.java
  src/main/java/com/umc/hwaroak/dto/response/FriendResponseDto.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/FriendService.java
  src/main/java/com/umc/hwaroak/serviceImpl/FriendServiceImpl.java
Labels: ✨ feature

#75 DEPLOY 1.4.1 - 회원 검색 기능 추가
  deploy.sh
  nginx/nginx.conf
  src/main/java/com/umc/hwaroak/controller/FriendController.java
  src/main/java/com/umc/hwaroak/dto/request/FriendRequestDto.java
  src/main/java/com/umc/hwaroak/dto/response/FriendResponseDto.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/service/FriendService.java
  src/main/java/com/umc/hwaroak/serviceImpl/FriendServiceImpl.java
Labels: 🌐 Deploy

#74 [Feat] 친구 페이지 방문하기
  src/main/java/com/umc/hwaroak/controller/DiaryController.java
  src/main/java/com/umc/hwaroak/controller/FriendController.java
  src/main/java/com/umc/hwaroak/dto/response/FriendResponseDto.java
  src/main/java/com/umc/hwaroak/repository/DiaryRepository.java
  src/main/java/com/umc/hwaroak/service/DiaryService.java
  src/main/java/com/umc/hwaroak/service/EmotionSummaryService.java
  src/main/java/com/umc/hwaroak/service/FriendService.java
  src/main/java/com/umc/hwaroak/serviceImpl/DiaryServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/EmotionSummaryServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/FriendServiceImpl.java
  src/main/java/com/umc/hwaroak/util/OpenAiUtil.java
Labels: ✨ feature

#78 refactor: 친구 요청시 단방향 관계만 체크하고 있던 문제 양방향 체크로 수정(#77)
  src/main/java/com/umc/hwaroak/domain/Friend.java
  src/main/java/com/umc/hwaroak/serviceImpl/FriendServiceImpl.java
Labels: 🐛 bug

#76 [feat] 마이페이지 관련 기능 구현
  src/main/java/com/umc/hwaroak/controller/EmotionSummaryController.java
  src/main/java/com/umc/hwaroak/controller/MemberController.java
  src/main/java/com/umc/hwaroak/dto/response/EmotionSummaryResponseDto.java
  src/main/java/com/umc/hwaroak/dto/response/MemberResponseDto.java
  src/main/java/com/umc/hwaroak/service/EmotionSummaryService.java
  src/main/java/com/umc/hwaroak/service/MemberService.java
  src/main/java/com/umc/hwaroak/serviceImpl/EmotionSummaryServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
Labels: ✨ feature

#87 [Fix] Alarm 전체 조회시 InfoDto에 isRead(알람 읽음) 여부 반환값 추가
  src/main/java/com/umc/hwaroak/dto/response/AlarmResponseDto.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmServiceImpl.java
Labels: 🐛 bug

#89 [fix] 회원, 감정분석, 알림 설정 관련 발생한 에러들 수정
  build.gradle
  src/main/java/com/umc/hwaroak/controller/AlarmSettingController.java
  src/main/java/com/umc/hwaroak/controller/MemberController.java
  src/main/java/com/umc/hwaroak/domain/AlarmSetting.java
  src/main/java/com/umc/hwaroak/domain/EmotionSummary.java
  src/main/java/com/umc/hwaroak/dto/response/AlarmSettingResponseDto.java
  src/main/java/com/umc/hwaroak/dto/response/MemberResponseDto.java
  src/main/java/com/umc/hwaroak/response/ErrorCode.java
  src/main/java/com/umc/hwaroak/serviceImpl/AlarmSettingServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/EmotionSummaryServiceImpl.java
  src/main/java/com/umc/hwaroak/serviceImpl/MemberServiceImpl.java
  src/main/java/com/umc/hwaroak/util/OpenAiUtil.java
Labels: 🚨 fix, 🐛 bug, ♻️ refactor
